entero=int(45)
print(entero)
flotante= float(45)
print(flotante)
largo=len("Hola")
print(largo)
cadena= str(45)
print(cadena)
redondeo=round(4.8)
print(redondeo)
redondeoDecimales=round(4.8647644, 2)
print(redondeoDecimales)
evaluar=eval("2+5")
print(evaluar)
valorAbsoluto= abs(-20)
print(valorAbsoluto)
binario= bin(45)
print(binario)
binarioEntero= int(0b101101)
print(binarioEntero)
hexadecimal= hex(45)
print(hexadecimal)
enteroHexa= int(0x2d)
print(enteroHexa)